plugins {
    id 'com.android.application'
}

android {
    namespace 'com.zqc.opencc.android'
    compileSdk 35
    // Only used to strip the library's native symbols when packaging.
    ndkVersion '27.2.12479018'

    defaultConfig {
        applicationId 'com.zqc.opencc.android'
        minSdk 21
        targetSdk 35
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation project(':lib-opencc-android')
    implementation 'androidx.appcompat:appcompat:1.7.0'
}
